upd test 4

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,24 +33,13 @@ jobs:
           echo "CLIENT_PORT=${{ secrets.CLIENT_PORT }}"
           echo "API_PORT=${{ secrets.API_PORT }}"
           echo "WS_PORT=${{ secrets.WS_PORT }}"
-          echo "DB_URL=${{ secrets.DB_URL }}"
-          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}"
-          echo "ROUTER_API=${{ secrets.ROUTER_API }}"
-          echo "JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_ACCESS_SECRET_KEY }}"
-          echo "JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_REFRESH_SECRET_KEY }}"
-          echo "SMTP_HOST=${{ secrets.SMTP_HOST }}"
-          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}"
-          echo "SMTP_USER=${{ secrets.SMTP_USER }}"
-          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}"
-          echo "API_URL=${{ secrets.API_URL }}"
         working-directory: ./client
       - name: Build the client Docker image
         run: |
           docker build . -t meet-app-client -f Dockerfile \
             --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
             --build-arg VITE_WS_URL=${{ secrets.VITE_WS_URL }} \
-            --build-arg CLIENT_PORT=${{ secrets.CLIENT_PORT }} \
-            --build-arg API_PORT=${{ secrets.API_PORT }} || { echo "Build failed"; exit 1; }
+            --build-arg CLIENT_PORT=${{ secrets.CLIENT_PORT }} || { echo "Build failed"; exit 1; }
         working-directory: ./client
       - name: Check images
         run: docker images | grep meet-app-client
