upd test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,6 +25,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: Debug environment variables
         run: |
+          echo "Checking secrets:"
           echo "VITE_API_URL=${{ secrets.VITE_API_URL }}"
           echo "VITE_WS_URL=${{ secrets.VITE_WS_URL }}"
           echo "CLIENT_PORT=${{ secrets.CLIENT_PORT }}"
@@ -32,7 +33,12 @@ jobs:
           echo "WS_PORT=${{ secrets.WS_PORT }}"
         working-directory: ./client
       - name: Build the client Docker image
-        run: docker build . -t meet-app-client -f Dockerfile --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} --build-arg VITE_WS_URL=${{ secrets.VITE_WS_URL }} --build-arg CLIENT_PORT=${{ secrets.CLIENT_PORT }} --build-arg API_PORT=${{ secrets.API_PORT }}
+        run: |
+          docker build . -t meet-app-client -f Dockerfile \
+            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
+            --build-arg VITE_WS_URL=${{ secrets.VITE_WS_URL }} \
+            --build-arg CLIENT_PORT=${{ secrets.CLIENT_PORT }} \
+            --build-arg API_PORT=${{ secrets.API_PORT }} || { echo "Build failed"; exit 1; }
         working-directory: ./client
       - name: Check images
         run: docker images | grep meet-app-client
@@ -43,7 +49,8 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - name: Build the auth-service Docker image
-        run: docker build . -t meet-app-server -f Dockerfile
+        run: |
+          docker build . -t meet-app-server -f Dockerfile || { echo "Build failed"; exit 1; }
         working-directory: ./backend/auth-service
       - name: Check images
         run: docker images | grep meet-app-server
diff --git a/client/Dockerfile b/client/Dockerfile
--- a/client/Dockerfile
+++ b/client/Dockerfile
@@ -1,9 +1,8 @@
 # Сборка зависимостей
 FROM node:20-alpine AS deps
 WORKDIR /app
-COPY ./package.json ./package.json
-COPY ./package-lock.json ./package-lock.json
-RUN npm install
+COPY ./package.json ./package-lock.json ./
+RUN npm install --no-optional
 
 # Сборка приложения
 FROM node:20-alpine AS builder
@@ -14,7 +13,7 @@ ARG VITE_API_URL
 ARG VITE_WS_URL
 ENV VITE_API_URL=$VITE_API_URL
 ENV VITE_WS_URL=$VITE_WS_URL
-RUN npm install -g npm@11.4.2 && npm run build
+RUN npm install && npm run build || { echo "Build failed"; exit 1; }
 # Отладка переменных
 RUN echo "VITE_API_URL=$VITE_API_URL" > /app/env-debug.txt
 RUN echo "VITE_WS_URL=$VITE_WS_URL" >> /app/env-debug.txt
